apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-deployment
spec:
  replicas: 1  # Número deseado de réplicas
  selector:
    matchLabels:
      app: fast-api-webapp
  template:
    metadata:
      labels:
        app: fast-api-webapp
    spec:
      containers:
      - name: fast-api-container
        image: ghcr.io/albertferal/liberandoproductos:1.0.12  # Reemplaza con tu imagen Docker
        ports:
        - containerPort: 8081  # Puerto expuesto por tu aplicación
        - containerPort: 8000  # Puerto para métricas y registros
