name: release-build

on:
  push:
    tags:
      - 'v*'
    
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Otros pasos según sea necesario

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Usar el token de GitHub para autenticación

      - name: Get the version to publish
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Build and push Docker image to GHCR
        run: |
          docker build -t ghcr.io/albertferal/LiberandoProductos:${{ steps.get_version.outputs.VERSION }} .
          docker push ghcr.io/albertferal/LiberandoProductos:${{ steps.get_version.outputs.VERSION }}
